name: ci

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'usage-demo/**'
      - '.gitignore'
    branches:
      - 'master'
      - 'main'
    tags:
      - '*'
  workflow_dispatch:
  schedule:
    - cron:  '0 21 * * 0,1,3,5'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build dockerfile (with push)
        run: |
            docker buildx build \
            --platform linux/amd64,linux/arm64/v8 \
            --output "type=image,push=true" \
            --file ./Dockerfile . \
            --tag dyrnq/nginx-proxy:latest
